apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: sum-vectors-app
  name: sum-vectors-app
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: sum-vectors-app
    spec:
      containers:
      - image: gcr.io/okpo-221120/okpo:1.0.4
        name: sum-vectors-app
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: sum-vectors-app
  name: sum-vectors-app
  namespace: default
spec:
  ports:
  - name: vectors-port-8989
    port: 8989
    targetPort: 8080
  - name: vectors-port-8080
    port: 8080
    targetPort: 8080
  selector:
    k8s-app: sum-vectors-app
---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: sum-vectors-app
#  labels:
#    team: frontend
#spec:
#  selector:
#    matchLabels:
#      app: sum-vectors-app
#  endpoints:
#  - port: vectors-port
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sum-vectors-app
  name: sum-vectors-app
  namespace: default
spec:
  endpoints:
  - interval: 5s
    port: vectors-port-8989
  - interval: 5s
    port: vectors-port-8080
  selector:
    matchLabels:
      k8s-app: sum-vectors-app
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: sum-vectors-app-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sum-vectors-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 2